/**
 * @file lv_conf.h
 * Configuration file for v9.2.0
 */

/* Minimal lv_conf.h generated by automated cleanup
 * Purpose: keep commonly used, enabled LVGL options for the project
 * and remove large disabled sections and verbose comments. Adjust as needed. */

#ifndef LV_CONF_H
#define LV_CONF_H

/* Basic color / resolution */
#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0
#define LV_HOR_RES_MAX 240
#define LV_VER_RES_MAX 320

/* Standard C library wrappers */
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB

/* Timing */
#define LV_TICK_CUSTOM 1
#if LV_TICK_CUSTOM
    #define LV_TICK_CUSTOM_INCLUDE "Arduino.h"
    #define LV_TICK_CUSTOM_SYS_TIME_EXPR (millis())
#endif

/* No RTOS in this project */
#define LV_USE_OS LV_OS_NONE

/* Rendering: use software renderer */
#define LV_USE_DRAW_SW 1
#if LV_USE_DRAW_SW
    #define LV_DRAW_SW_DRAW_UNIT_CNT 1
    #define LV_DRAW_SW_COMPLEX 1
    #define LV_DRAW_SW_LAYER_SIMPLE_BUF_SIZE (24 * 1024)
    #define LV_DRAW_SW_CIRCLE_CACHE_SIZE 4
    #define LV_USE_DRAW_SW_ASM LV_DRAW_SW_ASM_NONE
#endif

/* Logging and asserts kept enabled for debugging */
#define LV_USE_LOG 1
#if LV_USE_LOG
    #define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
    #define LV_LOG_PRINTF 1
    #define LV_LOG_USE_TIMESTAMP 1
    #define LV_LOG_USE_FILE_LINE 1
#endif

#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1

/* Core config */
#define LV_DEF_REFR_PERIOD 30
#define LV_DPI_DEF 130
#define LV_CACHE_DEF_SIZE 0
#define LV_IMAGE_HEADER_CACHE_DEF_CNT 0
#define LV_USE_PRIVATE_API 1

/* Fonts: enable common Montserrat sizes used by examples */
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_26 1
#define LV_FONT_DEFAULT &lv_font_montserrat_14
#define LV_USE_FONT_PLACEHOLDER 1

/* Text */
#define LV_TXT_ENC LV_TXT_ENC_UTF8

/* Widgets: only enable what the project uses (labels and generic objects).
 * The application uses only labels and generic containers created with
 * `lv_obj_create` + styles, so keep the widget list minimal. */
#define LV_USE_LABEL 1

/* No other widgets are enabled to reduce firmware size. Add back if needed. */

/* Themes & Layouts: disabled to keep config minimal; styles are applied directly */
#define LV_USE_THEME_DEFAULT 0


/* Third party / drivers used in this project */
#define LV_USE_TFT_ESPI 1
#define LV_USE_ILI9341 1

/* Keep examples disabled for smaller build */
#define LV_BUILD_EXAMPLES 0

/* End */
#endif /*LV_CONF_H*/